"""
Extract a single blueprint's full data as JSON.
Compatible with UE 5.7+ — uses T3D export for graph/variable data
and the asset registry for fast metadata.

Reads arguments from builtins._claude_args:
  - asset_path: The asset path to load (e.g., /Game/Blueprints/BP_Player)
  - output_file: Where to write the JSON output
"""

import json
import re
import os
import tempfile
import traceback
import unreal


def get_args():
    import builtins
    return getattr(builtins, '_claude_args', {})


# ── Asset Registry (fast metadata) ───────────────────────────────────────────

def get_registry_metadata(asset_path):
    """Return parent class, interfaces, and blueprint type from the asset registry."""
    meta = {
        'parentClass': '',
        'parentClassPath': '',
        'interfaces': [],
        'blueprintType': 'BPTYPE_Normal',
    }
    try:
        ad = unreal.EditorAssetLibrary.find_asset_data(asset_path)
        if not ad.is_valid():
            return meta

        parent = ad.get_tag_value('ParentClass') or ''
        m = re.search(r"'([^']+)'$", parent)
        if m:
            meta['parentClassPath'] = m.group(1)
            meta['parentClass'] = m.group(1).split('.')[-1]

        ifaces = ad.get_tag_value('ImplementedInterfaces') or ''
        for path in re.findall(r'Interface="([^"]+)"', ifaces):
            name = path.split('.')[-1].strip("'\"")
            if name.endswith('_C'):
                name = name[:-2]
            meta['interfaces'].append(name)

        meta['blueprintType'] = ad.get_tag_value('BlueprintType') or 'BPTYPE_Normal'
    except Exception:
        pass
    return meta


# ── T3D Export ────────────────────────────────────────────────────────────────

def export_t3d(asset_path):
    """Export blueprint to T3D text format. Returns (text, error_string)."""
    bp = unreal.EditorAssetLibrary.load_asset(asset_path)
    if bp is None:
        return None, f'Cannot load asset: {asset_path}'
    if not isinstance(bp, unreal.Blueprint):
        return None, f'Asset is not a Blueprint: {type(bp).__name__}'

    fd, tmp_path = tempfile.mkstemp(suffix='.t3d')
    os.close(fd)
    try:
        task = unreal.AssetExportTask()
        task.object = bp
        task.filename = tmp_path
        task.automated = True
        task.prompt = False
        task.exporter = unreal.ObjectExporterT3D()
        unreal.Exporter.run_asset_export_task(task)

        with open(tmp_path, 'r', encoding='utf-8', errors='replace') as f:
            return f.read(), None
    except Exception as e:
        return None, str(e)
    finally:
        try:
            os.unlink(tmp_path)
        except Exception:
            pass


# ── T3D Parser ────────────────────────────────────────────────────────────────
#
# T3D structure has two passes inside the outer Blueprint block:
#
#   First pass  — "Begin Object Class=X Name="Y"" — declares hierarchy, no properties
#   Second pass — "Begin Object Name="Y" ExportPath="...Class'...'"" — has properties+pins
#
# NewVariables appear as properties on the outer Blueprint block itself (after
# the second-pass graph redeclarations).

_RE_FIRST_PASS = re.compile(
    r'^Begin Object\s+Class=([^\s]+)\s+Name="([^"]+)"', re.IGNORECASE)

# Second-pass: no Class=, has ExportPath; extract class from "...Namespace.ClassName'..."
_RE_SECOND_PASS = re.compile(
    r'^Begin Object\s+Name="([^"]+)"\s+ExportPath="[^"]*?\.([^.\']+)\'', re.IGNORECASE)

_RE_END_OBJ  = re.compile(r'^End Object\s*$', re.IGNORECASE)
_RE_PROP     = re.compile(r'^(\w+(?:\(\d+\))?)\s*=\s*(.+)$')
_RE_CUST_PIN = re.compile(r'^CustomProperties Pin \((.+)\)\s*$')


def _parse_pin(pin_str):
    """Parse a CustomProperties Pin(...) string into a pin dict."""

    def rget(pattern, default=''):
        m = re.search(pattern, pin_str)
        return m.group(1) if m else default

    name      = rget(r'PinName="([^"]*)"')
    pin_id    = rget(r'PinId=([A-F0-9]{32})')
    direction = 'output' if 'Output' in rget(r'Direction="([^"]*)"') else 'input'
    hidden    = rget(r'bHidden=(True|False)') == 'True'

    # Build type string: prefer sub-category (float/double/int) over category (real/object)
    cat     = rget(r'PinType\.PinCategory="([^"]*)"')
    sub     = rget(r'PinType\.PinSubCategory="([^"]*)"')
    sub_obj = rget(r'PinType\.PinSubCategoryObject="([^"]*)"')

    if sub and sub not in ('', 'self', 'object', 'None'):
        pin_type = sub
    elif sub_obj and sub_obj not in ('', 'None'):
        # e.g. /Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Vector2D'
        pin_type = sub_obj.split('.')[-1].strip("'\"")
    else:
        pin_type = cat or 'unknown'

    # AutogeneratedDefaultValue often equals the user-set value (notably on
    # Set-node bool pins, where it mirrors the variable's BP default), so we
    # can't use it to suppress noise without erasing meaningful `true`/`false`.
    default_val  = rget(r'DefaultValue="([^"]*)"')
    show_default = default_val if default_val else None

    # Connections: LinkedTo=(NodeName PinGuid,). Encode each as "NodeName#PinId"
    # so the formatter can resolve the source pin by GUID (needed to follow
    # data wires through reroute/knot nodes and surface the real source).
    connected_to = []
    lm = re.search(r'LinkedTo=\(([^)]+)\)', pin_str)
    if lm:
        for m in re.finditer(r'(\w+)\s+([A-F0-9]{32})', lm.group(1)):
            connected_to.append(f'{m.group(1)}#{m.group(2)}')

    pin = {
        'name': name,
        'pinId': pin_id,
        'direction': direction,
        'type': pin_type,
        'connectedTo': connected_to,
    }
    if hidden:
        pin['hidden'] = True
    if show_default:
        pin['defaultValue'] = show_default
    return pin


def _parse_variable(val_str):
    """Parse a NewVariables(N)=(...) value string into a variable dict."""
    m = re.search(r'VarName="([^"]+)"', val_str)
    if not m:
        return None
    name = m.group(1)

    cat     = (re.search(r'PinCategory="([^"]*)"', val_str) or type('', (), {'group': lambda s, n: ''})()).group(1)
    sub     = (re.search(r'PinSubCategory="([^"]*)"', val_str) or type('', (), {'group': lambda s, n: ''})()).group(1)
    sub_obj = re.search(r'PinSubCategoryObject="([^"]*)"', val_str)

    if sub and sub not in ('', 'None'):
        type_str = sub
    elif sub_obj and sub_obj.group(1) not in ('', 'None'):
        type_str = sub_obj.group(1).split('.')[-1].strip("'\"")
    else:
        type_str = cat or 'unknown'

    # Category: extract English text from NSLOCTEXT("", "key", "Category Name")
    cat_name = ''
    ns_m = re.search(r'NSLOCTEXT\("[^"]*",\s*"[^"]*",\s*"([^"]+)"\)', val_str)
    if ns_m:
        cat_name = ns_m.group(1)

    # Friendly display name
    friendly_m = re.search(r'FriendlyName="([^"]+)"', val_str)
    friendly = friendly_m.group(1) if friendly_m else name

    # CPF_DisableEditOnInstance (0x8000) → not instance-editable
    flags_m = re.search(r'PropertyFlags=(\d+)', val_str)
    is_editable = True
    if flags_m:
        is_editable = not bool(int(flags_m.group(1)) & 0x8000)

    return {
        'name': name,
        'friendlyName': friendly,
        'type': type_str,
        'category': cat_name,
        'isEditable': is_editable,
        'isExposed': False,
    }


def _node_title(cls, props):
    """Derive a human-readable title for a blueprint node."""

    def _ref_name(ref_str):
        m = re.search(r'MemberName="([^"]+)"', ref_str)
        return m.group(1) if m else ''

    if cls == 'K2Node_Event':
        name = _ref_name(props.get('EventReference', ''))
        return f'Event {name}' if name else 'Event'

    if cls == 'K2Node_CustomEvent':
        name = props.get('CustomFunctionName', '').strip('"')
        return f'Custom Event: {name}' if name else 'Custom Event'

    if cls == 'K2Node_FunctionEntry':
        name = props.get('CustomFunctionName', '').strip('"') or \
               props.get('SignatureName', '').strip('"')
        return f'Function Entry: {name}' if name else 'Function Entry'

    if cls == 'K2Node_FunctionResult':
        return 'Return Node'

    if cls == 'K2Node_CallFunction':
        name = _ref_name(props.get('FunctionReference', ''))
        return name or 'Call Function'

    if cls == 'K2Node_VariableGet':
        name = _ref_name(props.get('VariableReference', ''))
        return f'Get {name}' if name else 'Get Variable'

    if cls == 'K2Node_VariableSet':
        name = _ref_name(props.get('VariableReference', ''))
        return f'Set {name}' if name else 'Set Variable'

    if cls == 'K2Node_IfThenElse':       return 'Branch'
    if cls == 'K2Node_ExecutionSequence': return 'Sequence'
    if cls == 'K2Node_Knot':              return 'Reroute'
    if cls == 'K2Node_Self':              return 'Self'
    if cls == 'K2Node_GetArrayItem':      return 'Get Array Element'
    if cls == 'K2Node_MakeArray':         return 'Make Array'
    if cls == 'K2Node_SpawnActorFromClass': return 'Spawn Actor From Class'

    if cls == 'K2Node_MacroInstance':
        ref = props.get('MacroGraphReference', '')
        m = re.search(r'MacroName="([^"]+)"', ref)
        return m.group(1) if m else 'Macro'

    if cls == 'K2Node_EnhancedInputAction':
        ia = props.get('InputAction', '')
        m = re.search(r"'([^']+)'$", ia)
        return f'Input: {m.group(1).split(".")[-1]}' if m else 'Enhanced Input Action'

    if cls == 'K2Node_Timeline':
        name = props.get('TimelineName', '').strip('"')
        return f'Timeline: {name}' if name else 'Timeline'

    if cls == 'K2Node_PromotableOperator':
        name = props.get('OperatorFunctionName', '').strip('"')
        return name or 'Operator'

    if cls == 'K2Node_DynamicCast':
        t = props.get('TargetType', '')
        m = re.search(r"'([^']+)'$", t)
        name = m.group(1).split('.')[-1] if m else t
        return f'Cast to {name}'

    if cls == 'K2Node_MakeStruct':
        t = props.get('StructType', '')
        m = re.search(r"'([^']+)'$", t)
        name = m.group(1).split('.')[-1] if m else t
        return f'Make {name}'

    if cls == 'K2Node_BreakStruct':
        t = props.get('StructType', '')
        m = re.search(r"'([^']+)'$", t)
        name = m.group(1).split('.')[-1] if m else t
        return f'Break {name}'

    if cls == 'EdGraphNode_Comment':
        text = props.get('NodeComment', '').strip('"')
        return f'// {text[:60]}' if text else 'Comment'

    # Strip common node prefixes for unknown types
    return re.sub(r'^(?:K2Node_|EdGraphNode_)', '', cls)


def _make_node(name, cls, props, pins):
    """Build a BlueprintNode dict from a second-pass T3D object block."""
    title = _node_title(cls, props)

    try:
        pos_x = int(props.get('NodePosX', '0').strip())
    except ValueError:
        pos_x = 0
    try:
        pos_y = int(props.get('NodePosY', '0').strip())
    except ValueError:
        pos_y = 0

    node_comment = props.get('NodeComment', '').strip('"')

    # Build clean pin list: skip hidden pins with no connections
    clean_pins = []
    for p in pins:
        if p.get('hidden') and not p['connectedTo']:
            continue
        cp = {
            'name':        p['name'],
            'pinId':       p.get('pinId'),
            'direction':   p['direction'],
            'type':        p['type'],
            'connectedTo': p['connectedTo'],
        }
        if p.get('defaultValue'):
            cp['defaultValue'] = p['defaultValue']
        clean_pins.append(cp)

    node = {
        'id':       name,
        'nodeGuid': _norm_guid(props.get('NodeGuid', '')),
        'type':     cls,
        'title':    title,
        'pins':     clean_pins,
        'position': {'x': pos_x, 'y': pos_y},
    }
    if node_comment:
        node['comment'] = node_comment

    # ── Type-specific extra fields ──────────────────────────────────────────

    if cls in ('K2Node_VariableGet', 'K2Node_VariableSet'):
        ref = props.get('VariableReference', '')
        m = re.search(r'MemberName="([^"]+)"', ref)
        if m:
            node['variable'] = m.group(1)

    if cls == 'K2Node_CallFunction':
        ref = props.get('FunctionReference', '')
        m_name   = re.search(r'MemberName="([^"]+)"', ref)
        m_parent = re.search(r'MemberParent=[^\'"]*[\'"]([^\'"]+)[\'"]', ref)
        if m_name:
            node['function'] = m_name.group(1)
        if m_parent:
            parent_cls = m_parent.group(1).split('.')[-1]
            is_self = 'bSelfContext=True' in ref
            if not is_self:
                node['functionClass'] = parent_cls

    if cls == 'K2Node_Event':
        ref = props.get('EventReference', '')
        m = re.search(r'MemberName="([^"]+)"', ref)
        if m:
            node['event'] = m.group(1)

    if cls == 'K2Node_CustomEvent':
        node['customEventName'] = props.get('CustomFunctionName', '').strip('"')

    if cls == 'K2Node_EnhancedInputAction':
        ia = props.get('InputAction', '')
        m = re.search(r"'([^']+)'$", ia)
        node['inputAction'] = m.group(1).split('.')[-1] if m else ia

    if cls == 'K2Node_Timeline':
        node['timelineName'] = props.get('TimelineName', '').strip('"')

    if cls == 'K2Node_MacroInstance':
        ref = props.get('MacroGraphReference', '')
        m = re.search(r'MacroName="([^"]+)"', ref)
        node['macroName'] = m.group(1) if m else ''

    if cls == 'EdGraphNode_Comment':
        node['commentText'] = props.get('NodeComment', '').strip('"')
        try:
            node['width']  = int(props.get('NodeWidth', '0'))
            node['height'] = int(props.get('NodeHeight', '0'))
        except ValueError:
            pass

    return node


# Properties on component templates that are UE-internal bookkeeping and
# add noise without value for code analysis.
_COMPONENT_PROP_BLOCKLIST = frozenset({
    'NodeGuid', 'VariableName', 'bRootComponent',
    'RelativeLocation', 'RelativeRotation', 'RelativeScale3D',
    'bIsEditorOnly', 'bNetAddressable', 'CreationMethod',
})


def _is_component_class(cls):
    """Return True if the T3D class name represents a UE component."""
    return cls.endswith('Component') or cls in ('DefaultSceneRoot', 'Scene', 'Billboard')


def parse_t3d(content):
    """
    Parse T3D content into variables, graphs, and component info.

    Returns a dict:
      {
        'variables': [...],
        'graphs': { graph_name: {'nodes': [...], 'comments': [...]} },
        '_raw_components': { name: {'type': str, 'props': {k: v}} },
      }
    """
    result = {
        'variables': [],
        'graphs': {},
        '_raw_components': {},
    }

    lines = content.splitlines()

    # Stack: list of dicts with keys: name, cls, is_first_pass, props, pins, graph
    stack = []

    for line in lines:
        s = line.strip()
        if not s:
            continue

        # ── Second-pass object (no Class= attribute) ────────────────────────
        m2 = _RE_SECOND_PASS.match(s)
        if m2:
            obj_name = m2.group(1)
            obj_cls  = m2.group(2)  # extracted from ExportPath

            # Determine current graph context from stack
            current_graph = next(
                (e['name'] for e in reversed(stack)
                 if e['cls'] == 'EdGraph' and not e['is_first_pass']),
                None
            )

            entry = {
                'name':          obj_name,
                'cls':           obj_cls,
                'is_first_pass': False,
                'props':         {},
                'pins':          [],
                'graph':         current_graph,
            }
            stack.append(entry)
            continue

        # ── First-pass object (has Class=) ─────────────────────────────────
        m1 = _RE_FIRST_PASS.match(s)
        if m1:
            obj_cls  = m1.group(1).split('.')[-1]
            obj_name = m1.group(2)
            entry = {
                'name':          obj_name,
                'cls':           obj_cls,
                'is_first_pass': True,
                'props':         {},
                'pins':          [],
                'graph':         None,
            }
            stack.append(entry)
            continue

        # ── End Object ──────────────────────────────────────────────────────
        if _RE_END_OBJ.match(s):
            if not stack:
                continue
            entry = stack.pop()

            if entry['is_first_pass']:
                # First-pass entries only carry NewVariables on the Blueprint block
                for key, val in entry['props'].items():
                    if key.startswith('NewVariables('):
                        var = _parse_variable(val)
                        if var:
                            result['variables'].append(var)
                continue

            # Second-pass processing
            cls  = entry['cls']
            name = entry['name']

            if cls == 'EdGraph':
                # Graph block itself: nothing to do (nodes were already added)
                pass
            elif _is_component_class(cls) and entry['graph'] is None:
                # Component template — collect overridden properties
                props = {
                    k: v for k, v in entry['props'].items()
                    if k not in _COMPONENT_PROP_BLOCKLIST
                }
                result['_raw_components'][name] = {'type': cls, 'props': props}
            elif entry['graph'] is not None:
                gname = entry['graph']
                if gname not in result['graphs']:
                    result['graphs'][gname] = {'nodes': [], 'comments': []}

                if cls == 'EdGraphNode_Comment':
                    node = _make_node(name, cls, entry['props'], entry['pins'])
                    result['graphs'][gname]['comments'].append(node)
                elif cls.startswith('K2Node_') or cls.startswith('AnimGraphNode_'):
                    node = _make_node(name, cls, entry['props'], entry['pins'])
                    result['graphs'][gname]['nodes'].append(node)
            continue

        # ── Inside an object: collect properties / pins ─────────────────────
        if not stack:
            continue

        top = stack[-1]

        # CustomProperties Pin
        mp = _RE_CUST_PIN.match(s)
        if mp:
            top['pins'].append(_parse_pin(mp.group(1)))
            continue

        # Regular property
        mpr = _RE_PROP.match(s)
        if mpr:
            top['props'][mpr.group(1)] = mpr.group(2).rstrip()

    return result


# ── Component tree builder ────────────────────────────────────────────────────

def _build_component_tree(raw_comps):
    """
    Convert the flat _raw_components dict into a BlueprintComponent tree.

    Parent-child relationships are derived from the AttachParent property
    (when present).  Components with no recognised parent become roots.
    """
    # Build node dicts
    nodes = {}
    for name, data in raw_comps.items():
        nodes[name] = {
            'name': name,
            'type': data['type'],
            'isRoot': False,
            'properties': data['props'],
            'children': [],
            '_parent_ref': data['props'].get('AttachParent', ''),
        }

    # Resolve AttachParent references.
    # The value looks like: SubobjectReference'...:ComponentName'
    # or just a component name after the last dot/colon.
    for name, node in nodes.items():
        ref = node.pop('_parent_ref')
        if not ref:
            continue
        # Extract the bare component name from the reference string
        m = re.search(r'[.:\'](\w+)(?:\'|$)', ref)
        if m:
            parent_name = m.group(1)
            if parent_name in nodes and parent_name != name:
                nodes[parent_name]['children'].append(node)
                node['_attached'] = True

    # Roots = nodes not attached to anything
    roots = [n for n in nodes.values() if not n.pop('_attached', False)]

    # Mark the most likely root component
    if len(roots) == 1:
        roots[0]['isRoot'] = True
    elif roots:
        for r in roots:
            if r['type'] in ('CapsuleComponent', 'SphereComponent', 'BoxComponent',
                             'DefaultSceneRoot', 'Scene') or 'Root' in r['name']:
                r['isRoot'] = True
                break
        else:
            roots[0]['isRoot'] = True

    return roots


# ── Graph classification ──────────────────────────────────────────────────────

# Graphs generated by the compiler or internal plumbing that aren't meaningful
# to expose to the user.
_INTERNAL_GRAPH_PATTERNS = re.compile(
    r'^(?:ExecuteUbergraph_|InpActEvt_|Timeline_+(?:Update|Finished)Func$|'
    r'.+_MERGED$|EdGraph_\d+$)'
)

def _is_internal(name):
    return bool(_INTERNAL_GRAPH_PATTERNS.match(name))


def _graph_to_function(name, gdata):
    """Build a function dict (signature + body nodes) from a function graph."""
    inputs, outputs = [], []
    for node in gdata['nodes']:
        if node['type'] == 'K2Node_FunctionEntry':
            for pin in node['pins']:
                if pin['direction'] == 'output' and pin['type'] != 'exec':
                    inputs.append({'name': pin['name'], 'type': pin['type']})
        elif node['type'] == 'K2Node_FunctionResult':
            for pin in node['pins']:
                if pin['direction'] == 'input' and pin['type'] != 'exec':
                    outputs.append({'name': pin['name'], 'type': pin['type']})
    return {
        'name':            name,
        'inputs':          inputs,
        'outputs':         outputs,
        'isPure':          False,
        'isStatic':        False,
        'accessSpecifier': 'public',
        'nodes':           gdata['nodes'],
        'connections':     _build_connections(gdata['nodes']),
    }


def _norm_guid(raw):
    """Normalise a T3D NodeGuid to FGuid Digits format (32 uppercase hex), matching the
    ids UClaudeBPGraphLibrary returns, so the read and write sides share one addressing scheme."""
    return re.sub(r'[^0-9A-Fa-f]', '', raw or '').upper()


def _build_connections(nodes):
    """Resolve each node's pin `connectedTo` refs (NodeName#PinId) into a normalised edge list
    keyed by NodeGuid + pin name on both ends, emitted once per edge (from output pins).
    Returns [{'from','fromPin','to','toPin','kind'}] where kind is 'exec' or 'data' — directly
    usable with edit-blueprint-graph's connect / breakPinLink ops."""
    name_to_guid = {}
    pin_name = {}
    for n in nodes:
        name_to_guid[n['id']] = n.get('nodeGuid', '')
        for p in n['pins']:
            pin_name[(n['id'], p.get('pinId'))] = p['name']
    edges = []
    for n in nodes:
        src_guid = n.get('nodeGuid', '')
        for p in n['pins']:
            if p.get('direction') != 'output':
                continue
            kind = 'exec' if p.get('type') == 'exec' else 'data'
            for ref in p.get('connectedTo', []):
                tgt_name, _, tgt_pid = ref.partition('#')
                tgt_guid = name_to_guid.get(tgt_name)
                tgt_pin = pin_name.get((tgt_name, tgt_pid))
                if tgt_guid and tgt_pin:
                    edges.append({
                        'from': src_guid, 'fromPin': p['name'],
                        'to': tgt_guid, 'toPin': tgt_pin, 'kind': kind,
                    })
    return edges


# ── Main extraction entry point ───────────────────────────────────────────────

def extract_blueprint(asset_path):
    """Load and extract full blueprint data. Returns a BlueprintInfo-compatible dict."""
    result = {
        'assetPath':      asset_path,
        'className':      asset_path.split('/')[-1],
        'parentClass':    '',
        'parentClassPath': '',
        'blueprintType':  '',
        'variables':      [],
        'functions':      [],
        'eventGraphs':    [],
        'components':     [],
        'interfaces':     [],
        'eventDispatchers': [],
    }

    # 1. Fast metadata from asset registry
    meta = get_registry_metadata(asset_path)
    result['parentClass']     = meta['parentClass']
    result['parentClassPath'] = meta['parentClassPath']
    result['interfaces']      = meta['interfaces']
    result['blueprintType']   = meta['blueprintType']

    # 2. Full graph/variable data via T3D export + parse
    t3d_text, err = export_t3d(asset_path)
    if err:
        result['_error'] = err
        return result

    parsed = parse_t3d(t3d_text)
    result['variables'] = parsed['variables']

    # Component tree
    raw_comps = parsed.get('_raw_components', {})
    if raw_comps:
        result['components'] = _build_component_tree(raw_comps)

    # 3. Organise graphs: event graphs go to eventGraphs, function graphs
    #    become BlueprintFunction entries with their nodes inlined.
    EVENT_GRAPH_NAMES = {'EventGraph', 'UserConstructionScript'}

    for gname, gdata in parsed['graphs'].items():
        if _is_internal(gname):
            continue

        if gname in EVENT_GRAPH_NAMES:
            result['eventGraphs'].append({
                'name': gname,
                'nodes': gdata['nodes'],
                'connections': _build_connections(gdata['nodes']),
            })
        else:
            result['functions'].append(_graph_to_function(gname, gdata))

    return result


def main():
    args        = get_args()
    asset_path  = args.get('asset_path', '')
    output_file = args.get('output_file', '')

    if not asset_path:
        data = {'error': 'No asset_path provided'}
    else:
        try:
            data = extract_blueprint(asset_path)
        except Exception as e:
            data = {'error': str(e), 'traceback': traceback.format_exc()}

    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str)
        unreal.log(f'[claude-unreal] Blueprint data written to {output_file}')
    else:
        unreal.log('[claude-unreal] No output_file specified')


# Run when invoked as the -run=pythonscript target (python-runner execs this file with
# __name__ == "__main__"); skipped when imported (e.g. by the round-trip regression test).
if __name__ == "__main__":
    main()
